### ISSUE TITLE
Добавьте в настройки возможность указать модель генерации

### ISSUE THREAD

**Issue by jurykor** [kodilo-inc/GPTRus-vscode-plugin#7]
Добавьте в настройки возможность указать модель генерации
[https://yandex.cloud/ru/docs/foundation-models/concepts/yandexgpt/models](https://yandex.cloud/ru/docs/foundation-models/concepts/yandexgpt/models)
чтобы не быть ограниченным yandexgpt-lite
modelUri: `gpt://${settings?.catalogueId}/${settings?.modelId}

**Comment by novitckas** [comment]
В коде поправил, но пока не опубликовал обновление в маркетплейсе. Как опубликую — отпишусь здесь

**Comment by novitckas** [comment]
@jurykor обновил расширение до версии 0.4.0 в маркетплейсе. Можно обновить расширение у себя в редакторе.
